{pkgs, ...}: {
  # Don't allow mutation of users outside the config.
  users.mutableUsers = false;

  programs.zsh.enable = true;
  users.users.wol = {
    initialHashedPassword = "$7$CU..../....UXUPPP01/OUQYSVEXQ54J/$tSPLuIKhOJeqCkZZT6omf7a2/K254dPSfVrQEGTKOR1"; # generated by `mkpasswd -m scrypt`
    home = "/home/wol";
    isNormalUser = true;
    shell = pkgs.zsh;
    extraGroups = [
      "adbusers"
      "i2c" # ddc support
      "input"
      "libvirtd"
      "networkmanager"
      "plugdev"
      "video"
      "wheel"
      "wireshark"
    ];
  };
}
